# Generated by Django 3.1.3 on 2020-11-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20201125_1442'),
        ('account', '0002_user_usercategorytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlleraccesstokens',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='controllerpasswordresettokens',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='manageraccesstokens',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='managerpasswordresettokens',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Controller',
        ),
        migrations.DeleteModel(
            name='ControllerAccessTokens',
        ),
        migrations.DeleteModel(
            name='ControllerPasswordResetTokens',
        ),
    ]
