# Generated by Django 3.1.3 on 2020-11-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201125_1442'),
        ('business', '0002_auto_20201125_1442'),
        ('wallet', '0002_auto_20201125_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='ManagerAccessTokens',
        ),
        migrations.DeleteModel(
            name='ManagerPasswordResetTokens',
        ),
    ]
