FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /c:/users/user/documents/storez
COPY requirements.txt /c:/users/user/documents/storez/
RUN pip install -r requirements.txt
COPY . /c:/users/user/documents/storez/
